# ---- GitHubæ–‡ä»¶æºé…ç½® ----
# GitHubç”¨æˆ·å(ä¸æ˜¯æ˜µç§°), æ³¨æ„å¤§å°å†™
GitHubUserName: "wl524035394"
# GitHubä¸»é¢˜ä»“åº“åç§°
GitHubRepositories: "wl524035394.github.io"


# ---- åŸºç¡€ä¿¡æ¯é…ç½® ----
# åšä¸»åç§°, æ–‡ç« åç¼€å’Œä¸»é¡µå›¾ç‰‡ä¸Šéƒ½ä¼šä½¿ç”¨æ­¤åç§°
User: "iLonge"
# ç”¨æˆ·å¤´åƒURL
UserAvatar: "/image/sidebar/avatar.png"
# åˆ›å»ºæ—¶é—´
WebsiteStartDate: "2025-02-09"
# ä¸ªäººä¸»é¡µURL
Home: "https://ilonge.cn"


# ---- ç½‘ç«™é…ç½® ----
# å½“å‰é¡µå¤±å»ç„¦ç‚¹, é¡µé¢Titleæ˜¾ç¤ºæ–‡å­—
WebsiteTitleBlur: "(â—Â´ê’³`â—) Hi, I`m ilongeï¼"
# å½“å‰é¡µå¤±å»ç„¦ç‚¹, é¡µé¢Titleå˜åŒ–, å»¶æ—¶æ—¶é—´, å•ä½æ¯«ç§’
WebsiteTitleBlurTimeOut: 500
# å½“å‰é¡µè·å–ç„¦ç‚¹, é¡µé¢Titleæ˜¾ç¤ºæ–‡å­—, æ˜¾ç¤ºåå»¶æ—¶æ¢å¤åŸTitle
WebsiteTitleFocus: "(*Â´âˆ‡ï½€*) æ¬¢è¿å›æ¥!"
# å½“å‰é¡µè·å–ç„¦ç‚¹, é¡µé¢titleå˜åŒ–, å»¶æ—¶æ—¶é—´, å•ä½æ¯«ç§’
WebsiteTitleFocusTimeOut: 800
# ç½‘ç«™å›¾æ ‡
WebsiteFavicon: 
  light: "/image/website/logo/logo.png"
  dark: "/image/website/logo/logo-dark.png"


# ---- è¿›åº¦æ¡é…ç½® ----
ProgressBar:
  id: "topProgressBar"
  color: "#77B6FF"
  height: "2px"
  duration: 0.2


# ---- Loadingé…ç½® ----
Loading: 
  rebound: 
    tension: 16
    friction: 5
  spinner: 
    id: "spinner"
    radius: 90
    sides: 3
    depth: 4
    colors: 
      background: "#F0F0F0"
      stroke: "#272633"
      base: null
      child: "#272633"
    # When false the spring will reverse normally.
    alwaysForward: true
    # A number from 0.1 to 0.9 || null for full rotation. 
    restAt: 0.5
    renderBase: false


# ---- é¡µé¢åŠ¨æ•ˆé…ç½® ----
# true || false, æ˜¯å¦æ¸²æŸ“ä¸»é¡µå¤´å›¾åŠ¨æ•ˆ
HomeHeaderAnimationRendered: true
# ä¸»é¡µå¤´å›¾åŠ¨æ•ˆè®¾ç½®
HomeHeaderAnimation:    
  radius: 15
  density: 0.2
  # é¢œè‰²è®¾ç½®, "random" ä¸ºéšæœºé¢œè‰²
  color: "rgba(255, 255, 255, .2)"
  clearOffset: 0.3
# true || false, æ˜¯å¦æ¸²æŸ“èƒŒæ™¯åŠ¨æ•ˆ
BackAnimationRendered: true
# true || false, IEæµè§ˆå™¨æ˜¯å¦æ¸²æŸ“èƒŒæ™¯åŠ¨æ•ˆï¼ˆé»˜è®¤ä¸ºfalseï¼‰
IEBrowserBackAnimationRendered: false
# èƒŒæ™¯åŠ¨æ•ˆè®¾ç½®
BackAnimation:
  colorSaturation: "60%"
  colorBrightness: "50%"
  colorAlpha: 0.5
  colorCycleSpeed: 5
  verticalPosition: "random"
  horizontalSpeed: 200
  ribbonCount: 3
  strokeSize: 0
  parallaxAmount: -0.2
  animateSections: true


# ---- ä¸»é¡µé…ç½® ----
# ä¸»é¡µå›¾ç‰‡URL, æ¨èå°ºå¯¸ >= 1920 * 1080, æ”¯æŒå¤šå¼ , æ¯æ¬¡åˆ·æ–°éšæœºè®¾ç½®ä¸€å¼ 
HomeHeaderImage: 
  - "/image/header/home.jpg"
  - "/image/header/home.jpeg"
  - "/image/header/future.jpg"
  - "/image/header/sea.jpg"
# ä¸»é¡µå¤´å›¾ä¸Šçš„æ ‡è¯­, è®¾ç½®æ­¤é€‰é¡¹ä¼šå›ºå®šæ˜¾ç¤ºæ–‡å­—, é»˜è®¤ä¸ºç©º, è‡ªåŠ¨è·å–ä¸€å¥
HomeBannerText: ""


# ---- æ–‡ç« è¯¦æƒ…é¡µé…ç½® ----
# æ–‡ç« è¯¦æƒ…é¡µå›¾ç‰‡URL, æ”¯æŒå¤šå¼ , æ¯æ¬¡åˆ·æ–°éšæœºè®¾ç½®ä¸€å¼ 
ArticleHeaderImage: 
  - "/image/header/article.jpg"


# ---- å…¶ä»–é¡µé¢é…ç½® ----
# å…¶ä»–é¡µé¢å¤´å›¾ä¸Šçš„æ ‡è¯­, è®¾ç½®æ­¤é€‰é¡¹ä¼šå›ºå®šæ˜¾ç¤ºæ–‡å­—, é»˜è®¤ä¸ºç©º, è‡ªåŠ¨è·å–ä¸€å¥
OtherBannerText: ""


# ---- é”™è¯¯é¡µé¢é…ç½® ----
Error:
  icon: "icon-swimming"
  title: "PAGE NOT FOUND"
  content:
    - "å¾ˆæŠ±æ­‰ï¼Œæ‚¨è®¿é—®çš„é¡µé¢ä¸å­˜åœ¨ï¼"
    - "å¯èƒ½æ˜¯è¾“å…¥åœ°å€æœ‰è¯¯æˆ–è¯¥åœ°å€å·²å˜æ›´ã€‚"
  buttons:
    - 
      icon: "icon-home"
      text: "è¿”å›é¦–é¡µ"
      href: "/"
      class: ""


# ---- èœå•é…ç½® ----
# èœå•æ¶ˆæ¯
MenuNotice:
  enable: true
  notice: "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ï¼Œå¾ˆé«˜å…´è§åˆ°ä½ ï¼"
  speed: 20
# èœå•åˆ—è¡¨
MenuList:
  -
    name: "é¦–é¡µ"
    icon: "icon-home-fill"
    href: "/"
    type: "index"
    class: ""
    target: "_self"
  - 
    name: "åˆ†ç±»"
    icon: "icon-folder-fill"
    href: "/category"
    type: "category"
    class: ""
    target: "_self"
  - 
    name: "æ ‡ç­¾"
    icon: "icon-discount-fill"
    href: "/tag"
    type: "tag"
    class: ""
    target: "_self"
  -
    name: "å½’æ¡£"
    icon: "icon-calendar-fill"
    href: "/archive"
    type: "archive"
    class: ""
    target: "_self"
  -
    name: "èµèµ"
    icon: "icon-heart-fill"
    href: "/donate"
    type: "donate"
    class: ""
    target: "_self"
  -
    name: "å…³äº"
    icon: "icon-about-fill"
    href: "/about"
    type: "about"
    class: ""
    target: "_self"
  -
    name: "è®¢é˜…"
    icon: "icon-rss"
    href: "/atom.xml"
    type: ""
    class: ""
    target: "_blank"
  -
    name: "æœç´¢"
    icon: "icon-search-menu"
    href: "javascript:;"
    type: ""
    class: "search"
    target: "_self"
  -
    name: "ç•™è¨€æ¿"
    icon: "icon-comments-fill"
    href: "/comment"
    type: "comment"
    class: ""
    target: "_self"
  -
    name: "å‹æƒ…é“¾æ¥"
    icon: "icon-link"
    href: "/friend"
    type: "friend"
    class: ""
    target: "_self"
# èœå•é“¾æ¥
MenuLink:
  -
    name: "çŸ¥ä¹"
    icon: "icon-zhihu"
    href: "https://zhihu.com/people/longe-40"
    class: ""
    target: "_blank"
    image: ""
  -
    name: "å¾®åš"
    icon: "icon-weibo"
    href: "https://weibo.com/u/1786198674"
    class: ""
    target: "_blank"
    image: ""
  -
    name: "QQ"
    icon: "icon-qq"
    href: "javascript:;"
    class: "image"
    target: "_self"
    image: "/image/sidebar/qq.png"
  -
    name: "å¾®ä¿¡"
    icon: "icon-wechat"
    href: "javascript:;"
    class: "image"
    target: "_self"
    image: "/image/sidebar/wechat.png"
  -
    name: "GitHub"
    icon: "icon-github"
    href: "https://github.com/wl524035394"
    class: ""
    target: "_blank"
    image: ""


# ---- é¡µè„šé…ç½® ----
# é¡µè„šæ ·å¼
FooterStyle: 2
# é¡µè„šæ ‡è¯­
BottomText: "<div><span class='face'>áƒ¦ã‚â—¡â•¹)ãƒâ™¡</span></div><div>ç”¨å¾®ç¬‘ğŸ˜Šé¢å¯¹ç”Ÿæ´»ï¼Œ<span></span>ç”Ÿæ´»ä¹Ÿä¼šå¯¹ä½ æŠ¥ä»¥å¾®ç¬‘<span style='color: red;'>â¤</span></div><div>&copy; 2025 WorstOne. All Rights Reserved.</div>"


# ---- æ§åˆ¶å°è¾“å‡º ----
ConsoleList:
  -
    - "Based on cnblogs theme SimpleMemory."
    - ""
  -
    - "SimpleMemory Author:"
    - "BNDong"
  -
    - "Theme:"
    - "LiveForCode"


# ---- å­—ä½“å›¾æ ‡æ‰©å±• ----
FontIconExtend: ""


# ---- èµèµé…ç½® ----
Donate: 
  paypal : ""
  bitcoin: ""
  alipay : "/image/donate/alipay.png"
  wechat : "/image/donate/wechat.png"


# ---- Algoliaé…ç½® ----
Search:
  applicationID: "OA1S361Y36"
  apiKey: "8ff306535844de1dfe36adfa8e96b57b"
  indexName: "ilonge"
  hits:
    page: 10
  labels:
    placeholder: "æœç´¢"
    empty: "æœªå‘ç°ä¸ ã€Œ${query}ã€ ç›¸å…³çš„å†…å®¹"
    stats: "${hits} æ¡ç›¸å…³æ¡ç›®ï¼Œä½¿ç”¨äº† ${time} æ¯«ç§’"


# ---- Commenté…ç½® ----
Comment:
  switch: true
  # é»˜è®¤ç±»å‹ä¸º Valine, å¯é€‰é¡¹ Waline Valine
  type: "Valine" 

# ---- Valineé…ç½® ----
Valine: 
  el: ".comments-content"
  appId: "aSDXzLSlip0GMsEfyZt3HX00-gzGzoHsz"
  appKey: "whnXfnjcoKbQyq2WdSJzrXFZ"
  # å¿…é¡»è®¾ç½®, å›½å†…ç‰ˆæœ¬éœ€åŸŸåå¤‡æ¡ˆ
  serverURLs:
  placeholder: "ä½ æ˜¯æˆ‘ä¸€ç”Ÿåªä¼šé‡è§ä¸€æ¬¡çš„æƒŠå–œ..."
  avatar: "monsterid"
  meta: ['nick','mail','link']
  requiredFields: ["nick","mail"]
  pageSize: 5
  lang: "zh-CN"
  visitor: true
  enableQQ: true
  recordIP: true  # æ˜¯å¦è®°å½•è¯„è®ºè€…IP

# ---- Walineé…ç½® ----
Waline:
  el: ".comments-content"
  serverURL: ""
  path: window.location.pathname
  meta: "['nick', 'mail', 'link']"
  requiredMeta: "['nick', 'mail']"
  pageSize: 10
  lang: "zh-cn"
  locale: 
      admin: "åšä¸»"
      anonymous: "åŒ¿åç”¨æˆ·"
      sofa: "å¿«æ¥åšç¬¬ä¸€ä¸ªè¯„è®ºçš„äººå§ ~"
      placeholder: "ä½ æ˜¯æˆ‘ä¸€ç”Ÿåªä¼šé‡è§ä¸€æ¬¡çš„æƒŠå–œ..."
  dark: "html[color-scheme='dark']"
  search: false
  pageview: true
  comment: true
  copyright: false


# ---- Tocboté…ç½® ----
Tocbot: 
  switch: true
  tocSelector: ".toc"
  contentSelector: ".article-body"
  headingSelector: "h1, h2, h3, h4, h5"
  headingsOffset: 0
  scrollSmooth: true
  scrollSmoothOffset: -5
  positionFixedSelector: ".toc"
  positionFixedClass: "toc-fixed"


# ---- Requireé…ç½® ----
Require:
  baseUrl: "/js/"
  waitSeconds: 100


# ---- Musicé…ç½® ----
# é»˜è®¤ä¸ºMeting, å€¼åŒ…å«APlayer, Meting
Music: 
  type: "Meting"
# APlayer
APlayer:
  container: ".aplayer"
  fixed: true 
  autoplay: false 
  loop: "all"
  order: "random"
  preload: "auto" 
  volume: 0.67 
  mutex: true
  lrcType: 3
  audio:
    -
      name: "Endless Tears"
      artist: "CLIFF EDGE"
      cover: "/music/cover/Endless Tears.jpg"
      url: "/music/song/Endless Tears.mp3"
      lrc: "/music/lrc/Endless Tears.lrc"
# Meting
Meting:
  api: "https://api.i-meto.com/meting/api"
  id: "3778678" 
  lrcshow: false 
  server: "netease" 
  type: "playlist"
  fixed: true 
  autoplay: false 
  loop: "all"
  order: "random"
  preload: "auto" 
  volume: 0.67 
  mutex: true


# ---- MouseåŠ¨ç”»é…ç½® ----
Mouse:
  enable: true
  options: 
    size: 6
    sizeF: 24


# ---- Lazy Load ----
LazyLoad:
  default: "/image/website/lazyload.svg"


# ---- Styleé…ç½® ----
Style:
  aplayer: "/css/APlayer.css"
  archive: "/css/archive.css"
  base: "/css/base.css"
  clipboard: "/css/clipboard.css"
  code: "/css/code.css"
  donate: "/css/donate.css"
  fancybox: "/css/jquery.fancybox.css"
  footer: "/css/footer.css"
  iconfont: "/iconfont/iconfont.css"
  index: "/css/index.css"
  menuBubble: "/css/menu-bubble.css"
  mouse: "/css/mouse.css"
  page: "/css/page.css"
  post: "/css/post.css"
  search: "/css/search.css"
  tocbot: "/css/tocbot.css"
  valine: "/css/valine.css"
  waline: "/css/waline.css"
  walineCustom: "/css/waline-custom.css"

# ---- Scripté…ç½® ----
Script:
  aplayer: "/js/APlayer.min.js"
  config: "/js/require.config.js"
  index: "/js/index.js"
  instantSearch: "/js/instantsearch.min.js"
  iscroll: "/js/iscroll.js"
  jQuery: "/js/jquery-3.4.1.min.js"
  loading: "/js/loading.js"
  meting: "/js/Meting.min.js"
  require: "/js/require.min.js"
  waline: "/js/waline.mjs"
  pageview: "/js/pageview.mjs"
  comment: "/js/comment.mjs"


# ---- Fonté…ç½® ----
Font:
  LongCang: "/font/LongCang.css"
  Monda: "/font/Monda.css"
  NotoSansSC: "/font/NotoSansSC.css"
  NotoSerifSC: "/font/NotoSerifSC.css"
  Playball: "/font/Playball.css"
  PTMono: "/font/PTMono.css"
  Roboto: "/font/Roboto.css"
  RobotoSlab: "/font/RobotoSlab.css"
  Rosario: "/font/Rosario.css"
  UbuntuMono: "/font/UbuntuMono.css"


# ---- æ–‡ç« å°¾ç¼€é…ç½® ----
Suffix: 
  about: "çˆ±ç”Ÿæ´»ï¼ŒiLongeã€‚"


# ---- ä¸»é¢˜ä¿¡æ¯é…ç½® ----
Theme: 
  url: "https://github.com/first19326/Hexo-LiveForCode"
  name: "Hexo - Live For Code"

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true